# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbdev-hello-world-2023',
                'doc_host': 'https://jeremybmerrill.github.io',
                'git_url': 'https://github.com/jeremybmerrill/nbdev-hello-world-2023',
                'lib_path': 'nbdev_hello_world_2023'},
  'syms': {'nbdev_hello_world_2023.core': {'nbdev_hello_world_2023.core.foo': ('core.html#foo', 'nbdev_hello_world_2023/core.py')}}}
